target: Chembl_Rank
base_path: /apdcephfs/private_jiaxianyan/git/UltraFlow
root_dir: /apdcephfs/private_jiaxianyan/git/UltraFlow/log
seed: 2022

train:
  gpu_memory_need: 2000
  repeat: 3
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 0.000
    dropout: 0.0
  scheduler:
    type: plateau
    factor: 0.6
    # factor: 0.95
    patience: 10
    min_lr: 1e-4
  gpus:
    - 0
    - 1
    - 2
    - 3
  resume_train: false
  resume_epoch: latest # IC50K ASRP reg reg 03 MTL AttentiveFP Flag correct batch 256 seed 2022
  resume_now: 2023-04-03_21:24:55
  batch_size: 64
  shuffle: true
  num_workers: 8
  use_memory_efficient_dataset: v2 # [v1, v2, false] , v1 split dataset, v2 do not prepare graph in advance
  pretrain_epochs: 100
  finetune_epochs: 1000
  early_stop: 70
  log_interval:
  eval: true
  save: true
  ranking_loss: pair_wise_v2 # [null, pair_wise_v1,pair_wise_v2]
  ranking_loss_lambda: 1.0
  pairwise_two_tower_regression_loss: false
  use_pretrain_model: true
  pretrain_ranking_loss: pairwise_v2 # [pairwise_v1, pairwise_v2], v1: image deepth prediction, v2: recommend system
  pretrain_sampling_method: pairwise_v1 # [pointwise, pairwise_v1]
  pretrain_ranking_loss_lambda: 1.0
  pretrain_regression_loss_lambda: 0.3
  pretrain_regression_loss_lambda_degrade_ratio: 1.0
  pretrain_regression_loss_lambda_degrade_epoch: 1
  pretrain_use_assay_description: false
  pretrain_assay_mlp_share: true
  pretrain_mtl_IC50_lambda: 1.0 # 0.2404, 0.3819
  pretrain_mtl_Kd_lambda: 1.0 # 0.4957
  pretrain_mtl_Ki_lambda: 1.0 # 0.2639
  pretrain_mtl_K_lambda: 1.0 # 0.6181
  multi_task: IC50K # [IC50KdKi, IC50K, false]
  finetune_times: 5
  finetune_new_affinity_head: false
  use_FLAG: false
  FLAG_step_size: 0.01
  FLAG_m: 4
  FLAG_v: v_inter
  encoder_ablation: null # [ligand, protein, interact, null]
  interact_ablate_op: min # [max, sum, mean, min]

test:
  epoch:
  now:

data:
  dataset_name: chembl_in_pdbbind_smina # [chembl_in_pdbbind_smina, chembl], chembl_smina: poses are generated by smina, chembl: poses are generated by UltraDock
  top_N: 1
  docking_type: site_specific  # [blind, site_specific, all]
  poses_select_rules: mbp_error_min # [mbp_error_min, mbp_error_threshold, random, null]
  confidence_threshold: 0.3
  use_ic50: true
  use_ki: true
  use_kd: true
  affinity_relation: '=' # [=, >, all], all: use > and =
  assay_des_type: BioLinkBERT_large_first_last_avg # [cls, first_last_avg, BioLinkBERT_large_cls, BioLinkBERT_large_first_last_avg, BioLinkBERT_large_last2avg, BioLinkBERT_large_last_avg]
  assay_des_dim: 1024
  #finetune_dataset_name: pdbbind2016_finetune  #pdbbind2020_no_add_h # pdbbind2016_finetune
  finetune_dataset_name: pdbbind2020_no_add_h
  generalize_dataset_name: csar_test
  split_type: assay_specific # [vertical, horizontal, assay_specific]
  drop_last: true
  dataset_path: ./UltraFlow/data
  #labels_path: ./UltraFlow/data/INDEX_general_PL_data.2016
  labels_path: ./UltraFlow/data/INDEX_general_PL_data.2020
  generalize_labels_path: ./UltraFlow/data/CSAR_NRC_HiQ_Set/SUMMARY_FILES/score_total.txt
  generalize_csar_test: ./UltraFlow/data/csar_2016
  vertical_train_names: ./UltraFlow/data/vertical_train_uniprots
  vertical_val_names: ./UltraFlow/data/vertical_valid_uniprots
  vertical_test_names: ./UltraFlow/data/vertical_test_uniprots
  horizontal_train_names: ./UltraFlow/data/horizontal_train.pkl
  horizontal_val_names: ./UltraFlow/data/horizontal_valid.pkl
  horizontal_test_names: ./UltraFlow/data/horizontal_test.pkl
  assay_specific_info: ./UltraFlow/data/vertical_total_smiles_and_uniprots
  assay_specific_train: ./UltraFlow/data/assay_specific_rank_pretrain_train
  assay_specific_valid: ./UltraFlow/data/assay_specific_rank_pretrain_valid
  chemb_smina_asrp_train: ./UltraFlow/data/chembl_smina_asrp_train
  chemb_smina_asrp_valid: ./UltraFlow/data/chembl_smina_asrp_valid
  finetune_train_names: ./UltraFlow/data/pdbbind2016_train_M
  #finetune_train_names: ./UltraFlow/data/pdbbind_2020_casf_train
  #finetune_train_names: ./UltraFlow/data/pdbbind2016_train
  finetune_train_names: ./UltraFlow/data/timesplit_no_lig_overlap_train
  #finetune_train_names: ./UltraFlow/data/pdbbind2016_general_train
  #finetune_valid_names: ./UltraFlow/data/pdbbind2016_valid_M
  #finetune_valid_names: ./UltraFlow/data/pdbbind2016_valid
  #finetune_valid_names: ./UltraFlow/data/pdbbind_2020_casf_valid
  finetune_valid_names: ./UltraFlow/data/timesplit_no_lig_overlap_val
  #finetune_valid_names: ./UltraFlow/data/pdbbind2016_general_valid
  #finetune_test_names: ./UltraFlow/data/pdbbind2016_test
  finetune_test_names: ./UltraFlow/data/timesplit_test
  #finetune_test_names: ./UltraFlow/data/pdbbind_2020_casf_test
  ligcut: 5.0  # null # 5.0
  add_chemical_bond_feats: true
  use_mean_node_features: false
  protcut: 30.0 # null # 30.0
  intercut: 12.0 # 8 # 12.0
  chaincut: 10
  prot_graph_type: residue_complete # atom_pocket # residue_complete
  n_jobs: 8
  lig_max_neighbors: null
  prot_max_neighbors: 10
  inter_min_neighbors: null
  inter_max_neighbors: null
  lig_type: openbabel
  test_2: false # test for asrp pretraining 
  test_100: false # test for finetune

model:
  model_type: Affinity_GNNs # [Affinity_GNNs, IGN, IGN_basic]
  GNN_type: AttentiveFP # [GCN, GAT, GIN, EGNN, AttentiveFP]
  out_dim: 1
  aux_dim: 8
  num_layers: 3
  hidden_dim: 128 # 128 #256  
  inter_out_dim: 128 # 128 # 200 
  fc_hidden_dim: [128,128,128] # [128, 128, 128] # [200,200,200]
  assay_des_fc_hidden_dim: [512] # [768, 512]
  fintune_fc_hidden_dim: [128] # [128] # [200]
  readout: w_sum_v2 # [w_sum, mean, max, sum, multi_head, w_sum_v2, multi_head_v2, w_sum_v3, multi_head_v3]
  num_head: 4
  attn_merge: concat # [concat, average]
  dropout: 0.1
  jk: sum

