target: Chembl_Rank
base_path: /apdcephfs/private_jiaxianyan/git/UltraFlow
root_dir: /apdcephfs/private_jiaxianyan/git/UltraFlow//log
seed: 2022

train:
  gpu_memory_need: 2000
  repeat: 3
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1e-6
    dropout: 0.0
  scheduler:
    type: plateau
    factor: 0.6
    # factor: 0.95
    patience: 10
    min_lr: 1e-4
  gpus:
    - 0
    - 1
    - 2
    - 3
  resume_train: false
  resume_checkpoint: null
  resume_epoch: null
  batch_size: 64
  shuffle: true
  num_workers: 1
  pretrain_epochs: 100
  finetune_epochs: 500
  early_stop: 70
  log_interval:
  eval: true
  save: true
  ranking_loss: null # [null, pairwise_v1, pairwise_v2]
  ranking_loss_lambda: 1.0
  regression_loss_lambda: 1.0
  use_pretrain_model: true
  pretrain_ranking_loss: pairwise_v2 # [pairwise_v1, pairwise_v2], v1: margin ranking loss, v2: binary cross entropy loss
  pretrain_sampling_method: pairwise_v1 # [pointwise, pairwise_v1]
  pretrain_ranking_loss_lambda: 1.0
  pretrain_regression_loss_lambda: 1.0
  pretrain_regression_loss_lambda_degrade_ratio: 1.0
  pretrain_regression_loss_lambda_degrade_epoch: 1
  pretrain_use_assay_description: true # false when pointwise
  pretrain_assay_mlp_share: true
  pretrain_mtl_IC50_lambda: 1.0 # 0.2404；0.3819
  pretrain_mtl_Kd_lambda: 1.0 # 0.4957
  pretrain_mtl_Ki_lambda: 1.0 # 0.2639
  pretrain_mtl_K_lambda: 1.0 # 0.6181
  multi_task: IC50K # [IC50KdKi, IC50K, false]
  finetune_times: 3
  finetune_new_affinity_head: false

test:
  epoch: 126
  finetune_epoch_list: [103, 162, 76]
  now: null

data:
  dataset_name: chembl_in_pdbbind_smina # [chembl_in_pdbbind_smina, chembl], chembl_smina: poses are generated by smina, chembl: poses are generated by UltraDock
#  affinity_type: IC50 # [IC50, ki, kd, all], all: use ki, kd, ic50
  use_ic50: true
  use_ki: true
  use_kd: true
  affinity_relation: = # [=, >, all], all: use > and =
  assay_des_type: first_last_avg # [cls, first_last_avg]
  assay_des_dim: 768 # 768 for PubChemBert, 1024 for BiolinkerBert
  finetune_dataset_name: pdbbind2020_finetune
  generalize_dataset_name: csar_test
  split_type: assay_specific # [vertical, horizontal, assay_specific]
  drop_last: true
  dataset_path: ./UltraFlow/data
  labels_path: ./UltraFlow/data/INDEX_general_PL_data.2020
  generalize_labels_path: ./UltraFlow/data/CSAR_NRC_HiQ_Set/SUMMARY_FILES/score_total.txt
  chemb_smina_asrp_train: ./UltraFlow/data/chembl_smina_asrp_train
  chemb_smina_asrp_valid: ./UltraFlow/data/chembl_smina_asrp_valid
  generalize_csar_test: ./UltraFlow/data/csar_2016
  finetune_train_names: ./UltraFlow/data/pdbbind2016_train
  finetune_valid_names: ./UltraFlow/data/pdbbind2016_valid
  finetune_test_names: ./UltraFlow/data/pdbbind2016_test
#  finetune_train_names: ./UltraFlow/data/pdbbind2020_finetune_train
#  finetune_valid_names: ./UltraFlow/data/pdbbind2020_finetune_valid
#  finetune_test_names: ./UltraFlow/data/pdbbind2020_finetune_test
  vertical_train_names: ./UltraFlow/data/vertical_train_uniprots
  vertical_val_names: ./UltraFlow/data/vertical_valid_uniprots
  vertical_test_names: ./UltraFlow/data/vertical_test_uniprots
  horizontal_train_names: ./UltraFlow/data/horizontal_train.pkl
  horizontal_val_names: ./UltraFlow/data/horizontal_valid.pkl
  horizontal_test_names: ./UltraFlow/data/horizontal_test.pkl
  assay_specific_info: ./UltraFlow/data/vertical_total_smiles_and_uniprots
  assay_specific_train: ./UltraFlow/data/assay_specific_rank_pretrain_train
  assay_specific_valid: ./UltraFlow/data/assay_specific_rank_pretrain_valid
  ligcut: 5.0
  protcut: 30.0
  intercut: 12.0
  chaincut: 10
  prot_graph_type: residue_complete
  n_jobs: 8
  lig_max_neighbors: null
  prot_max_neighbors: 10
  inter_min_neighbors: null
  inter_max_neighbors: null
  lig_type: openbabel
  test_2: false
  test_100: true

model:
  model_type: Affinity_GNNs # [Affinity_GNNs, IGN]
  GNN_type: GCN # [GCN, GIN, GAT, EGNN], parameter for Affinity_GNNs
  out_dim: 1
  aux_dim: 8
  num_layers: 3
  hidden_dim: 128
  inter_out_dim: 128
  fc_hidden_dim: [128,128,128]
  assay_des_fc_hidden_dim: [512] # [768, 512]
  fintune_fc_hidden_dim: []
  relation_fc_hidden_dim: []
  readout: w_sum
  dropout: 0.1
  jk: sum


